name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send push message to myself
        uses: appleboy/telegram-action@master
        # if: github.ref == 'refs/heads/dev'
        with:
          token: ${{ secrets.TGTOKEN }}
          to: ${{ secrets.TGTO_I }}
          message: "Опа! Произошел пуш номер ${{github.run_number}}:\n\n- ${{ join(github.event.commits.*.message, '\n\n- ') }}."
      - name: send push message to nik
        uses: appleboy/telegram-action@master
        # if: github.ref == 'refs/heads/dev'
        with:
          token: ${{ secrets.TGTOKEN }}
          to: ${{ secrets.TGTO_NIK }}
          message: "Опа! Произошел пуш номер ${{github.run_number}}:\n\n- ${{ join(github.event.commits.*.message, '\n\n- ') }}."
      - name: send push message to lar
        uses: appleboy/telegram-action@master
        # if: github.ref == 'refs/heads/dev'
        with:
          token: ${{ secrets.TGTOKEN }}
          to: ${{ secrets.TGTO_LAR }}
          message: "Опа! Произошел пуш номер ${{github.run_number}}:\n\n- ${{ join(github.event.commits.*.message, '\n\n- ') }}."
      - name: send push message to mik
        uses: appleboy/telegram-action@master
        # if: github.ref == 'refs/heads/dev'
        with:
          token: ${{ secrets.TGTOKEN }}
          to: ${{ secrets.TGTO_MIK }}
          message: "Опа! Произошел пуш номер ${{github.run_number}}:\n\n- ${{ join(github.event.commits.*.message, '\n\n- ') }}."
